"""Compatibility checking, baseline repair, and reporting helpers."""

from modpack_solver.solver.baseline import suggest_baseline_repairs
from modpack_solver.solver.checker import (
    CompatibilityReport,
    CompatibilityStatus,
    IssueSeverity,
    check_graph,
    check_synthetic_case,
    compute_status,
)
from modpack_solver.solver.explanations import (
    AlternativeExplanation,
    ExplanationReport,
    IssueExplanation,
    RepairExplanation,
    build_explanation_report,
    explain_issue,
    explain_solver_result,
    find_dependency_chain,
    format_compatibility_report,
    format_explanation_report,
    format_issue,
    format_repair_action,
)
from modpack_solver.solver.common import (
    SearchLimits,
    SolverComparison,
    SolverResult,
    SolverSolution,
    SolverStatus,
    compatible_versions_for_mod,
    evaluate_config,
    versions_for_mod,
)
from modpack_solver.solver.costs import RepairWeights, action_cost, plan_cost
from modpack_solver.solver.search import (
    apply_repair_action,
    generate_candidate_actions,
    search_weighted_repairs,
    solution_priority,
)
from modpack_solver.solver.state import (
    SolverState,
    add_selected_mod,
    canonical_state_key,
    count_original_mods_preserved,
    count_removed_original_mods,
    count_version_changes,
    remove_selected_mod,
    replace_selected_mod_version,
)
from modpack_solver.solver.weighted import (
    WeightedSolver,
    compare_baseline_and_weighted,
    solve_weighted,
    solve_weighted_case,
)

__all__ = [
    "CompatibilityReport",
    "CompatibilityStatus",
    "AlternativeExplanation",
    "ExplanationReport",
    "IssueExplanation",
    "IssueSeverity",
    "RepairExplanation",
    "RepairWeights",
    "SearchLimits",
    "SolverComparison",
    "SolverResult",
    "SolverSolution",
    "SolverState",
    "SolverStatus",
    "WeightedSolver",
    "action_cost",
    "add_selected_mod",
    "apply_repair_action",
    "canonical_state_key",
    "check_graph",
    "check_synthetic_case",
    "compare_baseline_and_weighted",
    "compatible_versions_for_mod",
    "compute_status",
    "count_original_mods_preserved",
    "count_removed_original_mods",
    "count_version_changes",
    "evaluate_config",
    "build_explanation_report",
    "explain_issue",
    "explain_solver_result",
    "find_dependency_chain",
    "format_compatibility_report",
    "format_explanation_report",
    "format_issue",
    "format_repair_action",
    "generate_candidate_actions",
    "plan_cost",
    "remove_selected_mod",
    "replace_selected_mod_version",
    "search_weighted_repairs",
    "solution_priority",
    "solve_weighted",
    "solve_weighted_case",
    "suggest_baseline_repairs",
    "versions_for_mod",
]
